
image: node:16

pipelines:
  branches:
    master:
       - step:
           name: Enviroment Setup
           script:
             - mkdir build
            #  - pwd
             - npm install
       - step:
            name: Build
            script:
             - npm run build
            artifacts:
             - build/**
      #  - step:
      #       name: Test
      #       script:
      #         - npm run test 
      #       artificats:
      #         - test/**     
       - step:
          name: Deploy to Production
          deployment: Production
          trigger: manual
          script:
            - pwd 
            - pipe: atlassian/aws-s3-deploy:1.1.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: 'us-east-1'
                S3_BUCKET: 'weather-bitbucket-pipeline'
                LOCAL_PATH: '/opt/atlassian/pipelines/agent/build'
     
